version: "3"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./init.sql:/init.sql
    env_file:
      - config.env
    deploy:
      resources:
        limits:
          memory: 4G
  app:
    build: ./src
    restart: always
    env_file:
      - config.env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.${TASK_NAME}.rule=Host(`${TASK_NAME}.web1.nto.sprush.rocks`)"
      - "traefik.http.services.${TASK_NAME}.loadbalancer.server.port=8337"

      - "traefik.http.routers.${TASK_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${TASK_NAME}.tls.certresolver=myresolver"