DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  is_admin boolean NOT NULL,
  secret TEXT
);

CREATE USER moderator WITH ENCRYPTED PASSWORD 'moderator';
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA information_schema, pg_catalog FROM PUBLIC;

GRANT EXECUTE ON FUNCTION int4(bigint) TO PUBLIC;
GRANT EXECUTE ON FUNCTION nextval(regclass) TO PUBLIC;
GRANT EXECUTE ON FUNCTION texteq TO PUBLIC;

GRANT SELECT,INSERT ON users TO moderator;
GRANT USAGE,SELECT ON SEQUENCE users_id_seq TO PUBLIC
