version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: MisterCreeper
      MYSQL_PASSWORD: MrsZombie
      MYSQL_DATABASE: BlockNaBlock
      MYSQL_ROOT_PASSWORD: EasyDiam0nds
    ports:
      - "3306"
    restart: on-failure

  web:
    build: ./src
    depends_on:
      - mysql
    volumes:
      - ./src:/src
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers 1 --access-logfile '-'
    environment:
      - flag=${flag}
      - flag_price=${flag_price}
      - balance_limit=${balance_limit}}
      - admin_name=${admin_name}
    restart: on-failure

    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.${TASK_NAME}.rule=Host(`${TASK_NAME}.web2.nto.sprush.rocks`)"
      - "traefik.http.services.${TASK_NAME}.loadbalancer.server.port=5000"

      - "traefik.http.middlewares.ip-hard-ratelimit.ratelimit.average=400"
      - "traefik.http.middlewares.ip-hard-ratelimit.ratelimit.burst=50"
      - "traefik.http.middlewares.ip-hard-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1"

      - "traefik.http.routers.${TASK_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${TASK_NAME}.tls.certresolver=myresolver"
      - "traefik.http.routers.${TASK_NAME}.middlewares=ip-hard-ratelimit@docker"
