version: '3.3'
services:
  pwn-warmup:
    read_only: true
    build: ./task
    container_name: pwn-warmup
    restart: always
    ports:
      - 51337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
