name: badusb
flag: "NTO{po_konyam_muzhiki_u_nas_incident}"
description: "Наш бухгалтер нашел какую-то флешку и первым делом вставил ее в свой компьютер! И ты еще в отпуске! Я снял все что мог, чтобы до конца недели расшифровал флаг."
