version: '3.3'
services:
  pwn-shock:
    read_only: true
    build: ./task
    container_name: pwn-shock
    restart: always
    ports:
      - 41337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
