#!/usr/bin/python3

import time
import random
from string import ascii_letters, digits
import os


def rnd_str():
    # weird
    return "".join(random.choice(ascii_letters + digits) for _ in range(5))


previous_fname = None
while True:
    fname = "/tmp/" + rnd_str()
    if fname == "weird":
        continue

    try:
        with open(fname, "w") as f:
            f.write(rnd_str())
    except IOError:
        pass

    if previous_fname:
        try:
            os.unlink(previous_fname)
        except OSError:
            pass

    previous_fname = fname

    time.sleep(20 + random.random() * 20)
