#!/usr/bin/python3

import time
import random
from string import ascii_letters, digits
import os


def rnd_str():
    # weird
    return "".join(random.choice(ascii_letters + digits) for _ in range(5))


previous_fname = None
while True:
    fname = "/tmp/weird"

    try:
        with open(fname, "w") as f:
            f.write(rnd_str())
            time.sleep(4 + random.random() * 5)
    except IOError:
        pass

    time.sleep(5 + random.random() * 5)
