version: '3.3'
services:
  pwn-skyfall:
    read_only: true
    build: ./task
    container_name: pwn-skyfall
    restart: always
    ports:
      - 61337:1337
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "256M"
